### ISSUE TITLE
Using different output path not working..

### ISSUE THREAD

**Issue by derekcollison** [matthodan/jekyll-asset-pipeline#1]
I am using the default gem install for both jekyll and jekyll-asset-pipeline. I also use compression.

I wanted my css assets to be under _site/assets/css, so I configured it appropriately.

``` yaml
asset_pipeline:
  compress: true           # Default = true
  output_path: assets/css  # Default = assets, but we just do css, but there is a bug..
```

Jekyl will output that the asset has been [re]generated, but the file is actually never written.
