### ISSUE TITLE
display_path isn't working with Octopress

### ISSUE THREAD

**Issue by coneybeare** [matthodan/jekyll-asset-pipeline#19]
```
# jekyll-asset-pipeline
asset_pipeline:
  bundle: true                                          # Default = true
  compress: true                                        # Default = true
  output_path: assets                                   # Default = assets
  display_path: http://site.com/blog                    # Default = nil
  gzip: true                                            # Default = false
```

and 

```
{% css_asset_tag global %}
- /_assets/stylesheets/screen.css
{% endcss_asset_tag %}  
{% javascript_asset_tag global %}
- /_assets/javascripts/modernizr-2.0.js
- /_assets/javascripts/ender.js
- /_assets/javascripts/octopress.js
{% endjavascript_asset_tag %}
```

renders

```
<link href='/assets/global-692dcc974a1799872aee8676b793b6e2.css' rel='stylesheet' type='text/css' />
<script src='/assets/global-f56b2ba0c79dc638d169c6ceb1751bff.js' type='text/javascript'></script>
```

but should render:

```
<link href='http://site.com/blog/assets/global-692dcc974a1799872aee8676b793b6e2.css' rel='stylesheet' type='text/css' />
<script src='http://site.com/blog/assets/global-f56b2ba0c79dc638d169c6ceb1751bff.js' type='text/javascript'></script>
```

right?
